# Generated by Django 5.2.5 on 2025-08-29 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="engineer",
            name="current_lat",
        ),
        migrations.RemoveField(
            model_name="engineer",
            name="current_lng",
        ),
        migrations.RemoveField(
            model_name="engineer",
            name="user",
        ),
        migrations.AddField(
            model_name="engineer",
            name="certifications",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="engineer",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="engineer",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="engineer",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="engineer",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="engineers/"),
        ),
        migrations.AddField(
            model_name="engineer",
            name="primary_skills",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="engineer",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="engineer",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="engineer",
            name="work_experience",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="engineer",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="engineer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="engineer",
            name="status",
            field=models.CharField(
                choices=[("online", "Online"), ("offline", "Offline")],
                default="offline",
                max_length=10,
            ),
        ),
    ]
