# Generated by Django 5.2.5 on 2025-08-29 08:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_engineer_current_lat_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="amount",
            new_name="per_hour_charge",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_no",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="paid",
        ),
        migrations.AddField(
            model_name="invoice",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="invoice",
            name="engineer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.engineer",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="hours_worked",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(default="INV-DEFAULT", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.job",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.client"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
