# Generated by Django 5.2.5 on 2025-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_amount_invoice_per_hour_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
